# Generated by Django 5.0.2 on 2025-08-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_appointment_medicalrecord_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_history',
            field=models.TextField(blank=True, help_text="Patient's medical history relevant to this appointment", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text="Doctor's notes about the appointment", null=True),
        ),
    ]
