# Generated by Django 5.0.2 on 2025-08-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_appointment_medical_history_appointment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsignup',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='patientsignup',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
